///测试demo数据,图片失效可自行替换,数据量可自行增加,结构不可更改

const Data = [
  {
    'id': 1,
    'name': '牛油鲜果沙拉',
    'price': 45.0,
    'url': 'https://www.itying.com/images/flutter/1.png',
    'mealType': '当日午餐',
  },
  {
    'id': 2,
    'name': '日本和牛牛排',
    'price': 85.0,
    'url': 'https://www.itying.com/images/flutter/2.png',
    'mealType': '当日午餐',
  },
  {
    'id': 3,
    'name': '水蜜桃甜品',
    'price': 60.0,
    'url': 'https://www.itying.com/images/flutter/3.png',
    'mealType': '次日晚餐',
  },
  {
    'id': 4,
    'name': '肯德基鸡肉卷',
    'price': 20.0,
    'url': 'https://www.itying.com/images/flutter/4.png',
    'mealType': '当日午餐',
  },
  {
    'id': 5,
    'name': 'M记嫩牛五方',
    'price': 35.0,
    'url': 'https://www.itying.com/images/flutter/5.png',
    'mealType': '次日晚餐',
  },
  {
    'id': 6,
    'name': '板烧猪扒包',
    'price': 50.0,
    'url': 'https://www.itying.com/images/flutter/6.png',
    'mealType': '当日午餐',
  },
  {
    'id': 7,
    'name': 'M记美式咖啡',
    'price': 45.0,
    'url': 'https://www.itying.com/images/flutter/7.png',
    'mealType': '当日午餐',
  },
  {
    'id': 8,
    'name': '牛油鲜果沙拉',
    'price': 45.0,
    'url': 'https://www.itying.com/images/flutter/1.png',
    'mealType': '当日午餐',
  },
  {
    'id': 9,
    'name': '日本和牛牛排',
    'price': 85.0,
    'url': 'https://www.itying.com/images/flutter/2.png',
    'mealType': '次日午餐',
  },
  {
    'id': 10,
    'name': '水蜜桃甜品',
    'price': 60.0,
    'url': 'https://www.itying.com/images/flutter/3.png',
    'mealType': '次日晚餐',
  },
  {
    'id': 11,
    'name': '肯德基鸡肉卷',
    'price': 20.0,
    'url': 'https://www.itying.com/images/flutter/4.png',
    'mealType': '当日午餐',
  },
  {
    'id': 12,
    'name': 'M记嫩牛五方',
    'price': 35.0,
    'url': 'https://www.itying.com/images/flutter/5.png',
    'mealType': '次日晚餐',
  },
  {
    'id': 13,
    'name': '板烧猪扒包',
    'price': 50.0,
    'url': 'https://www.itying.com/images/flutter/6.png',
    'mealType': '当日午餐',
  },
  {
    'id': 14,
    'name': 'M记美式咖啡',
    'price': 45.0,
    'url': 'https://www.itying.com/images/flutter/7.png',
    'mealType': '当日午餐',
  },
  {
    'id': 15,
    'name': '牛油鲜果沙拉',
    'price': 45.0,
    'url': 'https://www.itying.com/images/flutter/1.png',
    'mealType': '当日午餐',
  },
  {
    'id': 16,
    'name': '日本和牛牛排',
    'price': 85.0,
    'url': 'https://www.itying.com/images/flutter/2.png',
    'mealType': '次日午餐',
  },
  {
    'id': 17,
    'name': '水蜜桃甜品',
    'price': 60.0,
    'url': 'https://www.itying.com/images/flutter/3.png',
    'mealType': '次日晚餐',
  },
  {
    'id': 18,
    'name': '肯德基鸡肉卷',
    'price': 20.0,
    'url': 'https://www.itying.com/images/flutter/4.png',
    'mealType': '当日午餐',
  },
  {
    'id': 19,
    'name': 'M记嫩牛五方',
    'price': 35.0,
    'url': 'https://www.itying.com/images/flutter/5.png',
    'mealType': '次日晚餐',
  },
  {
    'id': 20,
    'name': '板烧猪扒包',
    'price': 50.0,
    'url': 'https://www.itying.com/images/flutter/6.png',
    'mealType': '当日午餐',
  },
];
